# Database Connection
spring.datasource.url=jdbc:sqlite:database/bdpm.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.sql.init.mode=never

spring.devtools.livereload.enabled=true
spring.devtools.restart.exclude=static/**,public/**

medixtractor.bdpm.default-source-dir=data/bdpm

# INSEE Sirene API Configuration
insee.api.key=927631ab-ed2d-43d8-b631-abed2d43d83f
insee.api.url=https://api.insee.fr/api-sirene/3.11
